### ISSUE TITLE
Add skipped dates error

### ISSUE THREAD

**Issue by georgemertz** [cbaron/patchwork#22]
If you have access to the database, you can try the exact situation. Went to customer 'Adam lee'. Tried to add skipped weeks to the 2017 Summer schedule. Tool gives an error,  but it actually writes it to the database. If you refresh the entry, meaning go back to search customers and re-load 'Adam lee' you find that the data was saved and a new transaction 'adjustment' is shown at the bottom, but it doesn't tell you that's what it did.

**Comment by cbaron** [comment]
Fixed locally.
