### ISSUE TITLE
Vegetable to never receive error

### ISSUE THREAD

**Issue by georgemertz** [cbaron/patchwork#23]
Suppose you want to change the vegetable to never receive. Select a new one, like lettuce. Then you think you think that's not right, so you want to remove it. You click on the 'x' next to the vegetable. The summary of changes does not update to reflect the removal of the 'lettuce' omission.  It won't let you submit the changes in this state, but it also doesn't remove the change to lettuce omission from the text.

It seems as though clicking the X next to the vegetable name contributes to some other errors too. Once I click that X, the summary of changes won't show changes to the payment plan, either. I haven't tried other fields, but suspect that there could be others that would be affected here.

**Comment by cbaron** [comment]
Just fixed it locally.  Thanks for taking the time.
