### ISSUE TITLE
Address text box

### ISSUE THREAD

**Issue by georgemertz** [cbaron/patchwork#24]
I'm not sure exactly what to do here, but I can identify that the address box on the customer info screen is very hard to read. I tried scrolling in and out to no avail. I couldn't find a spot that allowed me to see the whole address. Not a huge deal, but would be nice to be able to read it. Perhaps a smaller font for that box could help. Perhaps a wider box? Dunno.

**Comment by cbaron** [comment]
Yeah, sorry about this one, on my machine the scrollbar is invisible, so I didn't realize it would be an issue.
