### ISSUE TITLE
Multiple Changes to Order Options Error

### ISSUE THREAD

**Issue by georgemertz** [cbaron/patchwork#28]
Changed delivery option from 'on-farm' to 'Home' $17.50 to $20
Then change Share size from 'small' to 'large' $20 to $30 

Summary of changes gives the wrong 'weekly price adjustment'. It shows the base price to be $20, which includes the change from 'on-farm' to 'Home'. Then it adds $12.50 to that, and shows the new price is $32.50. It should actually show $30. A similar error occurs if you change delivery option from 'group' to 'home'.

Also, if you change the delivery option and hit 'reset', it doesn't reset. It stores the new delivery option and does so without saving the transaction at the bottom.

**Comment by georgemertz** [comment]
If you change the options independently and save them one-by-one, it works. So, hmpf.

**Comment by cbaron** [comment]
Just fixed these and updated the development site.
