### ISSUE TITLE
Change in Order Options then Change in Week Options Error

### ISSUE THREAD

**Issue by georgemertz** [cbaron/patchwork#29]
Looking at: Patchwork Gardens / 2017 Summer (5)

I was changing delivery option from 'on-farm' to 'home'
Then adding or removing delivery dates.

Without adding or removing dates, it shows an adjustment in the 'weeks added row' of the 'Adjust Member Share Options' summary at the bottom. If you select a week to not receive a box, then it shows an adjustment in that section. However, if you de-select that box back to the original setting, it shows a $17.50 credit even when there are zero weeks removed.

For some reason it starts by adding an extra week to the increased bill. Also, the 'Weeks affected' in the same section show 19 when it should be 14 to start.

**Comment by cbaron** [comment]
Just fixed this and pushed to the development site.
