### ISSUE TITLE
AdminTool Edit

### ISSUE THREAD

**Issue by cbaron** [cbaron/patchwork#39]
There is one thing that would be pretty helpful if we could fix. I'll describe the problem:

1. In the Admin Tool, we go to change a record for something. Say, in 'membershare'. Go to the bottom of the database, Edit the 2018 Spring signup for sidekick. 
2. Try to change the person from 'sidekick' to 'Laura A Krugh'. Do so by deleting 'sidekick' then typing 'Laura'. The autocomplete kicks in and you click on 'Laura A Krugh'. 
3. Then click inside a new box. Then click on 'Save'.

I think you'll see that it doesn't work. 

The only way we can get it to save is if you are selecting 'Laura A Krugh' and then hit enter without clicking out of the box you are editing. We have the same problem on any of the records we try to change in the admin tool.

**Comment by evanhsu** [comment]
When the 'Save' button is clicked, the following XHR request is sent to the server:
```
Request URL:http://localhost:4000/membershare/1475
Request Method:PATCH
Status Code:200 OK
Request Payload: {"paymentmethod":"Stripe"}
```

It looks like the payload is missing the `memberid:` and `shareid:` attributes.

Inspecting the `submit` event that gets 'emit'ed from the modal's `emitConfirmation()` method reveals the following data object:
`{memberid: "Laura A Krugh", shareid: "2018 Spring", paymentmethod: "Cash"}`

So it looks like the event contains the proper payload, but the final http request is somehow omitting part of the data.
