### ISSUE TITLE
Become a Member button does not submit to the backend.

### ISSUE THREAD

**Issue by cbaron** [cbaron/patchwork#41]
From a customer email:

```
I'm trying to sign up for the CSA again this year and I have all green checks by my CC info but when I hit "Become a Member" nothing happens. Help! 
```

This has been reported last season as well.  My guess is that its either a particular browser issue ( most of us use Chrome -- so does Patchwork, they cannot reproduce the bug )

Also, I think its likely it could be an autofill related error.

This being said, I have not looked at the code.

@cbaron

**Comment by evanhsu** [comment]
PR: https://github.com/cbaron/patchwork/pull/44
