### ISSUE TITLE
Cookie issue

### ISSUE THREAD

**Issue by cbaron** [cbaron/patchwork#43]
One patchwork employee was unable to receive the proper credentials via JWT token due to the fact that she was using the `www` subdomain.

Please update the `respondSetCookie` method in `./resources/util/User` in order to handle all patchwork subdomains and paths.

Something used in a previous repo

```
resources/auth.js:                'Set-Cookie': `${process.env.COOKIE}=${token}; Domain=comcast.tellient.com; Path=/; Expires=${new Date("2021-01-20").toUTCString()}`
```

Use env for Domain and cookie name

**Comment by evanhsu** [comment]
PR: https://github.com/cbaron/patchwork/pull/46
