### ISSUE TITLE
Sub header button placement

### ISSUE THREAD

**Issue by georgemertz** [cbaron/patchwork#52]
I know we've already toyed around with how to place the various subheading options, but what about something like the examples included.  "Member Sign In" tab could be on the far right with "CSA Sign up" button in the middle.  I was thinking that on the front page we may not need the "CSA Sign up" button since that page has the big, yellow Sign up button below.  Is it too weird to change the heading like that between pages?

So image one would be on all pages except the main page.  The second image would be on the main page only.

![header example](https://user-images.githubusercontent.com/26858929/37987984-b65ae37c-31cd-11e8-975f-dad09ee447d1.jpg)

![header example_front page only](https://user-images.githubusercontent.com/26858929/37987988-bbc053ec-31cd-11e8-8987-aeede4bcd288.jpg)

**Comment by ScottAP108** [comment]
I can do this, and I think it makes sense to have the CSA sign up link more prominent. My only concern is that the "Member Sign In" might get a bit lost among the other links. What do you think? Also, how would everything look when the member is signed in? In that case, you would need a "Sign Out" button as well as a link to the accounts section:  "Your Account". Would you want to have those two side by side at the end of the link list? Or would you want to keep the "Hello, Scott" menu that i have now with the sign out and account link inside that?

**Comment by georgemertz** [comment]
I think placing the Member Sign In to the far right ensures that it is noticeable.  Of course after the first time that a member locates it, they'll know where to find it!  I really like the "Hello, Scott" status when a member is signed in.  I think we should keep it that way and include "sign out" and "account" link within that drop-down menu.
